apiVersion: apps/v1
kind: Deployment
metadata:
  name: sald.in-deployment
spec:
  selector:
    matchLabels:
      app: homepage
  replicas: 1
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: sald-in
          image: sald-in
          ports:
            - containerPort: 80
