apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
images:
- name: sald-in
  newName: gcr.io/xxxaaaxxx/sald.in
  newTag: 6128d00f71f507d213a583ffb1ec9659139022bc
