version: '3.4'
services:
  frontend:
    image: sald.in:latest
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: static-html
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: saldin.iliya@gmail.com
    volumes:
      - ../conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
volumes:
  letsencrypt:
