# This is a basic workflow to help you get started with Actions

name: remote container restart

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: connect over ssh and restart container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SALDIN_HOST }}
          username: ${{ secrets.SALDIN_USERNAME }}
          password: ${{ secrets.SALDIN_PASSWORD }}
          script: cd /home/docker/sald.in && git pull && docker-compose -f docker/docker-compose.yml down && docker-compose -f docker/docker-compose.yml build && docker-compose -f docker/docker-compose.yml up -d
